//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int IdCandidato { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Edad { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public byte[] Foto { get; set; }
        public byte[] Curriculum { get; set; }
        public Nullable<int> IdUniversidad { get; set; }
        public Nullable<int> IdCarrera { get; set; }
        public Nullable<int> IdBolsaTrabajo { get; set; }
        public Nullable<int> IdVacante { get; set; }
    
        public virtual BolsaTrabajo BolsaTrabajo { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual Universidad Universidad { get; set; }
        public virtual Vacante Vacante { get; set; }
    }
}
