//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<byte> IdPiso { get; set; }
        public Nullable<int> IdCandidato { get; set; }
        public Nullable<byte> IdEstatusCita { get; set; }
        public string Url { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual EstatusCita EstatusCita { get; set; }
        public virtual Piso Piso { get; set; }
    }
}
